CREATE TABLE app_roles IF NOT EXISTS (
    id UUID PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE app_users IF NOT EXISTS (
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE KEY,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);